"""add_streaming_links_cache

Revision ID: 0358b0c32116
Revises: b0d2f998d79a
Create Date: 2026-01-04 22:51:42.619775
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0358b0c32116'
down_revision: Union[str, None] = 'b0d2f998d79a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('streaming_links', sa.JSON(), nullable=True))
    op.add_column('media', sa.Column('streaming_links_updated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'streaming_links_updated')
    op.drop_column('media', 'streaming_links')
    # ### end Alembic commands ###
