"""add_youtube_integration_fields

Revision ID: 2bdee57dc322
Revises: c3d4e5f6g7h8
Create Date: 2026-01-10 11:43:17.291290
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bdee57dc322'
down_revision: Union[str, None] = 'c3d4e5f6g7h8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('youtube_refresh_token', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('youtube_sync_enabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'youtube_sync_enabled')
    op.drop_column('users', 'youtube_refresh_token')
    # ### end Alembic commands ###
