"""add_youtube_playlist_id

Revision ID: 37a8f8eefd45
Revises: 2bdee57dc322
Create Date: 2026-01-10 12:03:30.775735
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37a8f8eefd45'
down_revision: Union[str, None] = '2bdee57dc322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('youtube_playlist_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'youtube_playlist_id')
    # ### end Alembic commands ###
