"""Add book ownership fields and BookLocation table

Revision ID: 6fd1af1d4d9f
Revises: 944ec3441d78
Create Date: 2026-01-07 13:00:08.617625
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fd1af1d4d9f'
down_revision: Union[str, None] = '944ec3441d78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('ownership_type', sa.Enum('NONE', 'PHYSICAL', 'EBOOK', 'BOTH', name='ownershiptype'), nullable=True))
    op.add_column('media', sa.Column('ownership_location', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'ownership_location')
    op.drop_column('media', 'ownership_type')
    # ### end Alembic commands ###
