"""add_current_episode_to_media

Revision ID: 944ec3441d78
Revises: bcb247d1d9dc
Create Date: 2026-01-07 11:14:09.555433
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '944ec3441d78'
down_revision: Union[str, None] = 'bcb247d1d9dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('current_episode', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'current_episode')
    # ### end Alembic commands ###
