"""add_extended_media_metadata

Revision ID: b0d2f998d79a
Revises: e9240c5c0156
Create Date: 2026-01-04 22:37:01.240990
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0d2f998d79a'
down_revision: Union[str, None] = 'e9240c5c0156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('tmdb_rating', sa.Float(), nullable=True))
    op.add_column('media', sa.Column('tmdb_vote_count', sa.Integer(), nullable=True))
    op.add_column('media', sa.Column('popularity', sa.Float(), nullable=True))
    op.add_column('media', sa.Column('budget', sa.Integer(), nullable=True))
    op.add_column('media', sa.Column('revenue', sa.Integer(), nullable=True))
    op.add_column('media', sa.Column('original_language', sa.String(length=10), nullable=True))
    op.add_column('media', sa.Column('production_countries', sa.JSON(), nullable=True))
    op.add_column('media', sa.Column('cast', sa.JSON(), nullable=True))
    op.add_column('media', sa.Column('keywords', sa.JSON(), nullable=True))
    op.add_column('media', sa.Column('collection_id', sa.Integer(), nullable=True))
    op.add_column('media', sa.Column('collection_name', sa.String(length=255), nullable=True))
    op.add_column('media', sa.Column('certification', sa.String(length=20), nullable=True))
    op.add_column('media', sa.Column('tagline', sa.String(length=500), nullable=True))
    op.add_column('media', sa.Column('number_of_seasons', sa.Integer(), nullable=True))
    op.add_column('media', sa.Column('number_of_episodes', sa.Integer(), nullable=True))
    op.add_column('media', sa.Column('series_status', sa.String(length=50), nullable=True))
    op.add_column('media', sa.Column('networks', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'networks')
    op.drop_column('media', 'series_status')
    op.drop_column('media', 'number_of_episodes')
    op.drop_column('media', 'number_of_seasons')
    op.drop_column('media', 'tagline')
    op.drop_column('media', 'certification')
    op.drop_column('media', 'collection_name')
    op.drop_column('media', 'collection_id')
    op.drop_column('media', 'keywords')
    op.drop_column('media', 'cast')
    op.drop_column('media', 'production_countries')
    op.drop_column('media', 'original_language')
    op.drop_column('media', 'revenue')
    op.drop_column('media', 'budget')
    op.drop_column('media', 'popularity')
    op.drop_column('media', 'tmdb_vote_count')
    op.drop_column('media', 'tmdb_rating')
    # ### end Alembic commands ###
