"""add tmdb_rating to recommendations

Revision ID: b1b57cea3bca
Revises: 5863967cd92d
Create Date: 2026-01-12 17:18:07.726038
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1b57cea3bca'
down_revision: Union[str, None] = '5863967cd92d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('tmdb_rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'tmdb_rating')
    # ### end Alembic commands ###
