"""Initial models

Revision ID: b51f48afdfff
Revises: 
Create Date: 2026-01-04 14:53:57.708841
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b51f48afdfff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.Enum('FILM', 'BOOK', 'YOUTUBE', name='mediatype'), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'media_type', name='uq_author_name_type')
    )
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('media_type', sa.Enum('FILM', 'BOOK', 'YOUTUBE', name='mediatype'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'media_type', name='uq_genre_name_type')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('FILM', 'BOOK', 'YOUTUBE', name='mediatype'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('original_title', sa.String(length=500), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('TO_CONSUME', 'IN_PROGRESS', 'FINISHED', 'ABANDONED', name='mediastatus'), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('jellyfin_id', sa.String(length=100), nullable=True),
    sa.Column('jellyfin_etag', sa.String(length=100), nullable=True),
    sa.Column('last_jellyfin_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'type', 'external_id', name='uq_media_user_type_external')
    )
    op.create_index(op.f('ix_media_external_id'), 'media', ['external_id'], unique=False)
    op.create_index(op.f('ix_media_jellyfin_id'), 'media', ['jellyfin_id'], unique=False)
    op.create_index(op.f('ix_media_status'), 'media', ['status'], unique=False)
    op.create_index(op.f('ix_media_type'), 'media', ['type'], unique=False)
    op.create_index(op.f('ix_media_user_id'), 'media', ['user_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_tag_user_name')
    )
    op.create_index(op.f('ix_tags_user_id'), 'tags', ['user_id'], unique=False)
    op.create_table('book_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('kobo_id', sa.String(length=100), nullable=True),
    sa.Column('progress_percent', sa.Float(), nullable=True),
    sa.Column('annotations', sa.JSON(), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_metadata_isbn'), 'book_metadata', ['isbn'], unique=False)
    op.create_index(op.f('ix_book_metadata_kobo_id'), 'book_metadata', ['kobo_id'], unique=False)
    op.create_index(op.f('ix_book_metadata_media_id'), 'book_metadata', ['media_id'], unique=True)
    op.create_table('film_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('resolution', sa.String(length=50), nullable=True),
    sa.Column('codec', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_film_metadata_media_id'), 'film_metadata', ['media_id'], unique=True)
    op.create_table('media_authors',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('media_id', 'author_id')
    )
    op.create_table('media_genres',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('media_id', 'genre_id')
    )
    op.create_table('media_tags',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('media_id', 'tag_id')
    )
    op.create_table('youtube_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=20), nullable=False),
    sa.Column('channel_name', sa.String(length=255), nullable=True),
    sa.Column('channel_id', sa.String(length=50), nullable=True),
    sa.Column('archived_path', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_youtube_metadata_media_id'), 'youtube_metadata', ['media_id'], unique=True)
    op.create_index(op.f('ix_youtube_metadata_video_id'), 'youtube_metadata', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_youtube_metadata_video_id'), table_name='youtube_metadata')
    op.drop_index(op.f('ix_youtube_metadata_media_id'), table_name='youtube_metadata')
    op.drop_table('youtube_metadata')
    op.drop_table('media_tags')
    op.drop_table('media_genres')
    op.drop_table('media_authors')
    op.drop_index(op.f('ix_film_metadata_media_id'), table_name='film_metadata')
    op.drop_table('film_metadata')
    op.drop_index(op.f('ix_book_metadata_media_id'), table_name='book_metadata')
    op.drop_index(op.f('ix_book_metadata_kobo_id'), table_name='book_metadata')
    op.drop_index(op.f('ix_book_metadata_isbn'), table_name='book_metadata')
    op.drop_table('book_metadata')
    op.drop_index(op.f('ix_tags_user_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_media_user_id'), table_name='media')
    op.drop_index(op.f('ix_media_type'), table_name='media')
    op.drop_index(op.f('ix_media_status'), table_name='media')
    op.drop_index(op.f('ix_media_jellyfin_id'), table_name='media')
    op.drop_index(op.f('ix_media_external_id'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('genres')
    op.drop_table('authors')
    # ### end Alembic commands ###
