"""Add Kobo integration columns to users table

Revision ID: b94c8bb0f23f
Revises: 6fd1af1d4d9f
Create Date: 2026-01-07 14:37:00.726359
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b94c8bb0f23f'
down_revision: Union[str, None] = '6fd1af1d4d9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_media_user_created', 'media', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_media_user_status', 'media', ['user_id', 'status'], unique=False)
    op.create_index('ix_media_user_type', 'media', ['user_id', 'type'], unique=False)
    op.create_index('ix_media_user_type_status', 'media', ['user_id', 'type', 'status'], unique=False)
    op.add_column('users', sa.Column('kobo_user_key', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('kobo_device_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'kobo_device_id')
    op.drop_column('users', 'kobo_user_key')
    op.drop_index('ix_media_user_type_status', table_name='media')
    op.drop_index('ix_media_user_type', table_name='media')
    op.drop_index('ix_media_user_status', table_name='media')
    op.drop_index('ix_media_user_created', table_name='media')
    # ### end Alembic commands ###
