"""add letterboxd_username to users

Revision ID: ccb480d0491c
Revises: e99ef9741126
Create Date: 2026-01-06 19:01:32.253030
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccb480d0491c'
down_revision: Union[str, None] = 'e99ef9741126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_user_created'), table_name='media')
    op.drop_index(op.f('ix_media_user_status'), table_name='media')
    op.drop_index(op.f('ix_media_user_type_status'), table_name='media')
    op.create_index(op.f('ix_media_streaming_links_updated'), 'media', ['streaming_links_updated'], unique=False)
    op.add_column('users', sa.Column('letterboxd_username', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'letterboxd_username')
    op.drop_index(op.f('ix_media_streaming_links_updated'), table_name='media')
    op.create_index(op.f('ix_media_user_type_status'), 'media', ['user_id', 'type', 'status'], unique=False)
    op.create_index(op.f('ix_media_user_status'), 'media', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_media_user_created'), 'media', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
