"""add_user_streaming_preferences

Revision ID: e9240c5c0156
Revises: 490cd92359d0
Create Date: 2026-01-04 22:27:04.545139
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9240c5c0156'
down_revision: Union[str, None] = '490cd92359d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country', sa.String(length=2), nullable=False, server_default='FR'))
    op.add_column('users', sa.Column('streaming_platforms', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'streaming_platforms')
    op.drop_column('users', 'country')
    # ### end Alembic commands ###
